name: Build VitePress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build VitePress
        run: npm run docs:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vitepress-build
          path: docs/.vitepress/main

      - name: Send update signal.
        run: |
          latest_commit_hash=$(git rev-parse HEAD)
          curl -X GET https://apiv3.hayfrp.com/updateRepo?repo=learn&commit=$latest_commit_hash


